apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: demo
  name: demo
spec:
  ports:
    - name: 8087-8087
      port: 8087
      protocol: TCP
      targetPort: 8087
  selector:
    app: demo
  type: ClusterIP
status:
  loadBalancer: {}
